[조조] 쿠폰 수정 기능 동시성 문제 해결
jewelry-box/java-coupon pull request #2
Opened 2024-12-18 07:52 UTC by eun-byeol

2024-12-19 19:54 UTC, linirini requested changes
조조~ 반가와용 ㅎㅎ 리니입니다❣️
조조는 비관적 락을 선택하셨네요! 아무래도 돈이 관련된 동시성 문제이다보니 납득되는 선택이라고 생각해요!

미션 요구사항에는 `두 대의 DB를 사용하며 회원에게 발급된 쿠폰과 쿠폰 저장소를 분리하는 작업을 계획 중`이라고 했는데 그 과정에서 락 관리가 복잡해질 우려는 없었나요? (일종의 분산 시스템이 될 수 있다고 생각해요, 분산 DB 환경에서는 데이터가 여러 노드(서버)에 나뉘어 저장되고, 각 노드는 독립적으로 데이터와 트랜잭션을 관리할텐데, 이로 인해 비관적 락을 적용하기 어려워질 수 있다고 생각했습니다!)
또한 데드락과 데이터베이스 레벨에서의 락으로 인한 네트워크 지연에 대한 조조의 생각이 궁금합니다!

2024-12-19 19:54 UTC, linirini commented on src/main/java/coupon/domain/Coupon.java
> +        validate(discountAmount, minOderAmount);
(별거 아님 주의 2)
메서드 순서 컨벤션 한 번 확인 부탁드려요~

2024-12-19 19:54 UTC, linirini commented on src/main/java/coupon/repository/CouponRepository.java
> +    @Lock(LockModeType.PESSIMISTIC_WRITE)
[소소한 퀴즈]
LockModeType에는 어떤 것들이 있나요?

2024-12-19 19:54 UTC, linirini commented on src/main/java/coupon/repository/CouponRepository.java
> +    @Lock(LockModeType.PESSIMISTIC_WRITE)
비관적 락의 종류는 어떤 것들이 있나요?

2024-12-19 19:54 UTC, linirini commented on src/main/java/coupon/repository/CouponRepository.java
> +    Optional<Coupon> findByIdForUpdate(long couponId);
[soso 퀴즈]
비관적 락은 어느 시점에 충돌을 감지하나요?

2024-12-19 19:54 UTC, linirini commented on src/main/java/coupon/service/CouponReader.java
> +public class CouponReader {
Reader와 Writer 클래스를 분리했네요! 이러한 결정을 한 이유가 궁금합니다~

2024-12-19 19:54 UTC, linirini commented on src/main/java/coupon/domain/Coupon.java
> +    public Coupon setDiscountAmount(DiscountAmount discountAmount) {
(별거 아님 주의!)
setter 네이밍을 따르다보니 반환값이 있는지 모를 수도 있을 것 같아요! 네이밍을 바꿔보는 것도 괜찮을지도...?

2024-12-19 19:54 UTC, linirini commented on src/main/java/coupon/repository/CouponRepository.java
> +    @Lock(LockModeType.PESSIMISTIC_WRITE)
사용자 1이 수정하는 데이터에 사용자 2가 동시에 조회를 시도한다면 어떻게 되나요?

2024-12-21 11:56 UTC, cutehumanS2 requested changes
우형의 new 딸랑구 조조, 안녕하세요. 냥인입니다. 😸
리뷰가 많이 늦어져서 죄송합니다. ㅜ.ㅜ 나태함.. . . 고칠게요!

조조는 비관적 락을 적용하셨군여~ 머니는 소중하죠. ㅎ ㅎ
DB 락과, DB와 캐시의 일관성에 대해 리뷰를 쪼끔 남겨보았습니다. 
천천히~ 생각해 보셔요. ✿ܓ

2024-12-21 11:56 UTC, cutehumanS2 commented on docker/reader/docker-entrypoint.sh
> +/usr/bin/mysql -uroot -p'root' -S /var/run/mysqld/mysqld.sock -e "CREATE DATABASE IF NOT EXISTS coupon"
데이터베이스 생성문을 1) 이 스크립트에 포함하는 것과 2) 기존 방식이었던 걸로 추정되는 init.sql 파일에 포함하는 방식의 차이점이 무엇인가요? 

요 방식에 대해 어떻게 알게 되셨나요?! 🫢

2024-12-21 11:56 UTC, cutehumanS2 commented on src/main/java/coupon/domain/Coupon.java
> +    public Coupon setMinOrderAmount(MinOrderAmount minOderAmount) {
minOderAmount << 요기 오타가 있네요 ㅎ.ㅎ O 뒤에 r 빠짐요 ㅎㅎ

2024-12-21 11:56 UTC, cutehumanS2 commented on src/main/java/coupon/service/CouponService.java
> +    }
[궁금]
updateDiscountAmount()가 실패해도 DB의 데이터와 캐시 데이터의 일관성이 보장되나요? 둘의 데이터 불일치 가능성은 없을까요??

2024-12-21 11:56 UTC, cutehumanS2 commented on src/main/java/coupon/repository/CouponRepository.java
> +    @Lock(LockModeType.PESSIMISTIC_WRITE)
1) 이렇게 걸린 락은 언제 해제되나요? 
2) 그리고 이 락은 테이블 전체에 걸리나요, 레코드에 걸리나요?

2024-12-21 11:56 UTC, cutehumanS2 commented on README.md
> +- Coupon 엔티티에 @DynamicUpdate 어노테이션 설정
왜 3단계 미션에서 @DynamicUpdate를 적용하라 했을까요?? ✦‿✦

2024-12-22 15:04 UTC, jongmee requested changes
굿이예요 👍 궁금한 거 몇 개 리뷰 남겨보았습니다 ㅎㅎ

2024-12-22 15:04 UTC, jongmee commented on src/main/java/coupon/repository/CouponRepository.java
> +    @Lock(LockModeType.PESSIMISTIC_WRITE)
> 처음엔 낙관적 락으로 구현해보았으나,
10개의 동시 테스트를 진행할 때에도 정합성이 잘 지켜지지 않았습니다. 0.1초 sleep 후 100번 재시도 할 때에도 모든 요청이 처리되지 않더라구요. (버전 카운트 수로 모든 요청이 db에 반영되었는지로 판단했습니다)

낙관적 락을 사용했을 때 이 시나리오는 왜 발생하게 되는지 설명해주실 수 있나요 ?? 궁금합니다 ㅎㅎ 🤔

2024-12-22 15:04 UTC, jongmee commented on src/main/java/coupon/service/CouponService.java
> +    @CachePut(value = "coupon", key = "#couponId")
스프링에서 제공하는 AOP 애너테이션을 적절히 사용해주셨군요 👍 `@CachePut`은 어떤 원리로 동작하나요?? (AOP 동작 원리 말고 AOP 기반으로 동작하는 캐시 매커니즘이 궁금합니다!)

2024-12-22 15:04 UTC, jongmee commented on src/main/java/coupon/repository/CouponRepository.java
> +    Optional<Coupon> findByIdForUpdate(long couponId);
mysql x-lock을 사용했을 때 느낀 단점은 없었나요?? 궁금합니다 ㅎㅎ

2024-12-26 14:09 UTC, eun-byeol commented on README.md
> +- Coupon 엔티티에 @DynamicUpdate 어노테이션 설정
동적 쿼리를 만들어주기 위함입니다.
hibernate는 기본적으로 모든 칼럼 값을 변경하는 SQL을 생성합니다. 어노테이션으로 특정 칼럼(할인금액, 최소주문금액)에 해당하는 동적 쿼리만 생성할 수 있습니다.

2024-12-26 14:09 UTC, eun-byeol commented on docker/reader/docker-entrypoint.sh
> +/usr/bin/mysql -uroot -p'root' -S /var/run/mysqld/mysqld.sock -e "CREATE DATABASE IF NOT EXISTS coupon"
1)SQL 쿼리 명령어를 직접 실행하느냐, 2)SQL 파일로 만들어 실행하느냐의 차이입니다. 이전 리뷰이였던 안나를 통해 알게되었습니다!
사실 명령어 실행 자체에는 큰 차이가 없습니다.
init.sql 방식으로 실행 시에 복제지연이 잘 되지 않았어요. DDL은  만들어지는데, write DB에 생성된 데이터가 read DB로 복제가 안 됐어요. 아직 이유는 파악하지 못했지만 미션 진행을 위해 ddl-auto를 validate에서 update로 우선 변경해두었습니다. sql 파일을 지우다보니 SQL 쿼리 명령어로 데이터베이스를 생성하는 것이 간편해서 커멘드 라인에서 실행하게 했습니다.

2024-12-26 14:09 UTC, eun-byeol commented on src/main/java/coupon/domain/Coupon.java
> +    public Coupon setDiscountAmount(DiscountAmount discountAmount) {
(반영 완) 오 별거인걸요? 좋습니다~

2024-12-26 14:09 UTC, eun-byeol commented on src/main/java/coupon/domain/Coupon.java
> +    public Coupon setMinOrderAmount(MinOrderAmount minOderAmount) {
(반영 완) 오호👍

2024-12-26 14:09 UTC, eun-byeol commented on src/main/java/coupon/domain/Coupon.java
> +        validate(discountAmount, minOderAmount);
(반영 완) 마지막으로 사용하는 public 메서드 아래로 옮겨주었습니다. 원래는 첫번째 public 메서드 바로 아래에 놓는 편인데, 정돈되지 않아 보일 수도 있겠네요!

2024-12-26 14:09 UTC, eun-byeol commented on src/main/java/coupon/repository/CouponRepository.java
> +    @Lock(LockModeType.PESSIMISTIC_WRITE)
> LockModeType 종류

- `READ` : 읽기 락(주로 JPA 캐시에서 사용)
- `WRITE` : 쓰기 락(주로 JPA 캐시에서 사용)
- `OPTIMISTIC` : 낙관적 락(데이터 수정시에만 버전 업)
- `OPTIMISTIC_FORCE_INCREMENT` : 낙관적 락(데이터 조회시에도 버전 업)
- `PESSIMISTIC_READ` : 비관적 락(S-Lock. DB에서 지원하지 않으면 X-Lock(for update)으로 대체)
- `PESSIMISTIC_WRITE` : 비관적 락(X-Lock)
- `PESSIMISTIC_FORCE_INCREMENT` : 버전 필드 사용하는 비관적 락(X-Lock. 데이터 조회시에도 버전 업)
- `NONE` : No lock

[참고](https://willbfine.tistory.com/576)

2024-12-26 14:09 UTC, eun-byeol commented on src/main/java/coupon/repository/CouponRepository.java
> +    @Lock(LockModeType.PESSIMISTIC_WRITE)
> 비관적 락의 종류

- 공유락(S-Lock) : select for share. 공유락이 걸린 데이터에 `공유락은 가능하지만, 배타락은 불가능`
- 배타락(X-Lock) : select for update. 배타락이 걸린 데이터에 `공유락과 배타락 불가능`

2024-12-26 14:09 UTC, eun-byeol commented on src/main/java/coupon/repository/CouponRepository.java
> +    @Lock(LockModeType.PESSIMISTIC_WRITE)
> 사용자 1이 수정하는 데이터에 사용자 2가 동시에 조회를 시도한다면 어떻게 되나요?

PESSIMISTIC_WRITE 모드의 경우 사용자 1에서 배타락을 걸게 됩니다.
사용자 2의 경우 락이 없는 일반 select 문의 경우 조회가 가능하고(SERIALIZABLE 격리수준이 아니라면)
select for share 같은 공유락의 경우, 락을 획득하기 위해 대기합니다.

2024-12-26 14:09 UTC, eun-byeol commented on src/main/java/coupon/repository/CouponRepository.java
> +    @Lock(LockModeType.PESSIMISTIC_WRITE)
1. 기본적으로는 트랜잭션 종료 시점(커밋 or 롤백)입니다. MySQL InnoDB의 경우 잠금 대기 타임아웃 기능(기본 50초)을 제공하고 있어, 해당 시간 내 잠금이 해제되지 않으면 트랜잭션이 실패하여 락을 해제할 수 있습니다.

2. MySQL InnoDB 엔진을 사용하고 있어, 레코드 락(X-Lock)이 걸립니다.

2024-12-26 14:09 UTC, eun-byeol commented on src/main/java/coupon/repository/CouponRepository.java
> +    @Lock(LockModeType.PESSIMISTIC_WRITE)
사실 해당 시나리오는 비관적/낙관적 락을 구현하고 성능 테스트해보기 위함이었어요. 그래서 어느정도 동시 상황이 있다고 가정했습니다. 10개의 동시 테스트 코드를 짜두고, 낙관적 락과 비관적 락을 각각 적용해서 구현해보았습니다.
실제로는 10개 동시 상황이 발생하는 시나리오는 의미가 크진 않을 것 같아요. 그래서 실제로 구현된 테스트 코드도 2개 동시 테스트이구요.

2024-12-26 14:09 UTC, eun-byeol commented on src/main/java/coupon/repository/CouponRepository.java
> +    Optional<Coupon> findByIdForUpdate(long couponId);
락 획득을 시도하는 시점입니다~! 반대로 낙관적 락은 트랜잭션 커밋 시점입니다.

2024-12-26 14:09 UTC, eun-byeol commented on src/main/java/coupon/repository/CouponRepository.java
> +    Optional<Coupon> findByIdForUpdate(long couponId);
체감한 단점은 없었어요.

주로 언급되는 단점이 `데드락`과 `동시성이 낮다`는 점인데,
MySQL InnoDB의 경우 타임아웃(innodb_lock_wait_timeout : 기본 50초)이나 데드락 자동 감지 기능(innodb_deadock_detect)을 제공하고 있어요. 물론, 동시 처리하는 스레드가 많아지면 데드락 자동 감지로 인한 성능 저하가 있어 off로 두기도 한다고 합니다.

동시성에 대한 부분도 체감할만큼은 아니었어요. S-Lock과 비교해보진 못했지만, 동시 요청 수가 적을때는 낙관적 락이나 비관적 락(X-Lock) 모두 응답시간이 짧았어요. 오히려 동시 요청수가 크면 클수록 낙관적 락이 소요시간이 (거짓말 살짝 보태서) 기하급수적으로 커지더라구요. 재시도 로직을 두다보니 더 오래 걸리긴 했습니다.

2024-12-26 14:09 UTC, eun-byeol commented on src/main/java/coupon/service/CouponReader.java
> +public class CouponReader {
`레플리케이션 환경`과 `재사용성` 때문입니다.
1. 레플리케이션 환경에서, Writer는 WriteDB를 사용하고 Reader는 ReaderDB를 사용하도록 명시하고자 했어요. `@Transactional` 어노테이션으로 WriteDB, ReadDB 커넥션을 구분하고 있다보니, 트랜잭션 전파로 인해 의도와 달리 ReadDB가 읽히지 않는 경우도 발생했었어요. 물론 트랜잭션 전파 속성을 REQUIRES_NEW로 둬서 `readOnly=true`를 명시할 수도 있었지만, 오히려 코드가 복잡해졌어요. 로직도 직관적이지 않았구요.
2. Reader의 `findById()` 재사용성을 높이기 위함도 있었어요. Reader의 findById()는 캐시를 먼저 보고 > 없으면, ReadDB를 확인하고 > 없으면, WriteDB를 확인하는 방식으로 동작해요. 조회가 필요한 경우 최대한 해당 메서드를 재활용하고 싶었습니다.

물론, 현재 로직이 간단해서 분리할 필요성이 크진 않아요. 오히려 레이어가 많아져 복잡하게 느껴질 수도 있어요. 기능 확장을 하다가 불필요해지는 시점에 지워질 수 있는 부분이라고 생각합니다!

참고
- [지속 성장 가능한 소프트웨어를 만들어가는 방법](https://geminikims.medium.com/%EC%A7%80%EC%86%8D-%EC%84%B1%EC%9E%A5-%EA%B0%80%EB%8A%A5%ED%95%9C-%EC%86%8C%ED%94%84%ED%8A%B8%EC%9B%A8%EC%96%B4%EB%A5%BC-%EB%A7%8C%EB%93%A4%EC%96%B4%EA%B0%80%EB%8A%94-%EB%B0%A9%EB%B2%95-97844c5dab63)
- [Reader, Writer 쓰지말자 (feat. implement layer)](https://www.youtube.com/watch?v=EIOVlBWisas)

2024-12-26 14:09 UTC, eun-byeol commented on src/main/java/coupon/service/CouponService.java
> +    }
오호.. 좋은 포인트이네요👍
캐시와 DB 데이터 일관성 보장됩니다.
DiscountAmount 제약조건 맞지 않는 경우(100원)로 테스트해봤는데, 캐시에서 조회한 데이터와 DB 데이터 일치했어요.

해당 로직 상에서 그외 불일치 가능성은 없어보여요.
다만, `TTL 설정이 되지 않았다는 점`과 다른 수정 로직을 만들었는데 `캐시 업데이트 하지 않은 경우`가 데이터 일관성이 불일치할 수 있는 가능성이 있을 것 같아요.

2024-12-26 14:09 UTC, eun-byeol commented on src/main/java/coupon/service/CouponService.java
> +    @CachePut(value = "coupon", key = "#couponId")
`@CachePut`은 해당 어노테이션이 붙은 메서드 실행 이후 메서드 반환값을 캐싱해요. 특이한 점은 메서드의 실행과 별개로 동작해요. 즉, `couponWriter.updateDiscountAmount()`이 캐시 데이터에 상관 없이 항상 실행합니다(조회 시 캐시 데이터 사용X). 뭐가 특이하지 했는데, 반대로 `@Cacheable`은 캐시를 사용해서 메서드 실행을 건너 뛸 수 있어요. 즉, 캐시에 데이터가 있으면 `couponWriter.updateDiscountAmount()`를 실행하지 않아요.

디버깅 툴로 확인해보니 메서드 실행 이후에 [CacheAspectSupport](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/cache/interceptor/CacheAspectSupport.html)에 의해서 AOP 캐싱 로직을 수행하고 있었어요.

참고해보면 좋을 블로그 [1](https://mangkyu.tistory.com/370), [2](https://velog.io/@semi-cloud/%EC%8A%A4%ED%94%84%EB%A7%81-%EC%BA%90%EC%8B%9C-%EC%A0%81%EC%9A%A9-%EA%B3%BC%EC%A0%95%EC%97%90%EC%84%9C%EC%9D%98-%EC%82%BD%EC%A7%88%EA%B8%B0)
혹시, 제가 다르게 이해한 부분있으면 말씀해주세요!

2025-01-06 10:37 UTC, linirini commented on src/main/java/coupon/domain/Coupon.java
> +        validate(discountAmount, minOderAmount);
조조의 컨벤션에 대한 이해가 부족했네요😅
어떤 방식으로 정렬하는지 이해했습니다! 편하신대로 정렬해주세용~

2025-01-06 10:40 UTC, linirini commented on src/main/java/coupon/service/CouponReader.java
> +public class CouponReader {
> @Transactional 어노테이션으로 WriteDB, ReadDB 커넥션을 구분하고 있다보니, 트랜잭션 전파로 인해 의도와 달리 ReadDB가 읽히지 않는 경우도 발생했었어요. 물론 트랜잭션 전파 속성을 REQUIRES_NEW로 둬서 readOnly=true를 명시할 수도 있었지만, 오히려 코드가 복잡해졌어요. 로직도 직관적이지 않았구요.

오홍!!!

좋은 레퍼런스도 공유해주셔서 감사해요❣️

2025-01-06 10:47 UTC, linirini approved these changes
조조❣️달아주신 코멘트 모두 확인했습니다. 딱히 추가적으로 드릴 피드백은 없는 것 같아서 approve 합니다! 오히려 제가 reader와 writer에 대한 추가 인사이트를 얻어가는 것 같네요 ㅎㅎ
비관적 락을 사용해보지 않았는데, 조조 덕분에 간접적으로 경험할 수 있었어요! 저도 다음에 시도해봐야겠슴당👍
수고하셨어옹~

2025-01-08 06:48 UTC, cutehumanS2 commented on src/main/java/coupon/repository/CouponRepository.java
> +    @Lock(LockModeType.PESSIMISTIC_WRITE)
굿👍 조조가 말씀하신 대로 couponId가 PK인 경우, InnoDB는 해당 레코드의 인덱스 엔트리에 대해 레코드 수준의 잠금을 수행하겠져~ㅎ ㅎ

2025-01-08 06:51 UTC, cutehumanS2 approved these changes
조조 안녕하세요 ㅎ.ㅎ 냥인입니다. 😸
리뷰 반영 아주 성실히 해주셨군요! 남겨주신 답변 모두 확인하였어요. 

이만 어푸르브 할게요! 조조도 새해 복 많이 받으세요~~🤍 🖤

2025-01-14 07:59 UTC, jongmee approved these changes
남겨준 코멘트 모두 잘 읽었습니다! 고생하셨읍니다 🤍

2025-01-15 06:03 UTC, merged