[리니] 쿠폰 수정 기능 동시성 문제 해결
jewelry-box/java-coupon pull request #4
Opened 2024-12-18 13:42 UTC by linirini

아직 완성을 못했습니다...ㅜㅜ
최대한 빠르게 완성해놓겠습니다. 죄송합니다 ㅜㅜ

2024-12-20 04:29 UTC, eun-byeol reviewed
리니🎶 조조입니다~
낙관적 락에 대한 근거 잘 말씀해주셔서 납득되었어요!
간단한 리뷰들 남겼으니 확인해주세요!

> 캐싱이 제대로 되지 않는 문제

1. 캐시에 null 값이 저장되는 문제
`@CachePut` 사용한 메서드에 반환값이 없어서 coupon에 null 값이 저장되고 있었어요.
반환값을 만들어줘야 합니다!

2. coupon 조회 시 null 값이 들어가는 문제
위 문제를 해결해도, coupon 필드들에 null이 들어가고 있었어요.
시간관계상 직접 해결은 못해보았는데, 
레디스 캐시 데이터를 보니 value로 id값만 저장되고 있는 것 같아요. 다른 필드들도 잘 저장되는지 확인해봐야 할것 같습니다!
key = `"coupons::1"`
value = `"[\"coupon.coupon.domain.Coupon\",{\"id\":[\"java.lang.Long\",1]}]"`

2024-12-20 04:29 UTC, eun-byeol commented on src/main/java/coupon/coupon/domain/Coupon.java
> +    @Version
[질문22]
수정 시점에만 엔티티 버전을 증가시키는 방법을 선택한 이유가 궁금해요! `@Version`만 붙이면 기본적으로 LockModeType.NONE으로 지정되는 것으로 알고 있는데, OPTIMISTIC 같은 다른 전략은 선택하지 않은 이유가 있을까요?

2024-12-20 04:29 UTC, eun-byeol commented on docker/init/schema.sql
> +    end_at               DATETIME(6)                                              NOT NULL,
[퀴즈~]
논외이지만, datetime과 timestamp는 어떤 차이가 있을까요?

2024-12-20 04:29 UTC, eun-byeol commented on src/main/java/coupon/coupon/service/CouponService.java
> +    @CachePut(value = "coupons", key = "#p0")
[제안]
`#id` 파라미터 이름을 사용하면 컴파일 시점에 잡아줄 수 있어요!

2024-12-20 04:29 UTC, eun-byeol commented on src/main/java/coupon/coupon/service/CouponService.java
> +    @Retry
[질문]
springboot의 `@Retryable`를 사용하지 않고 직접 AOP로 만들어준 이유가 있을까요?🤔

2024-12-20 04:29 UTC, eun-byeol commented on src/main/java/coupon/util/OptimisticLockRetryAspect.java
> +@Order(Ordered.LOWEST_PRECEDENCE - 1)
[질문]
우선순위를 뒤에서-1로 지정해준 이유가 무엇인가요?

2024-12-20 04:29 UTC, eun-byeol commented on src/main/java/coupon/util/OptimisticLockRetryAspect.java
> +    private static final int RETRY_DELAY_MILLISECONDS = 100;
[질문]
재시도 횟수와 딜레이를 설정한 근거가 궁금해요!
지금은 update를 위한 재시도 로직밖에 없지만, 다른 로직을 위한 재시도가 생긴다면 어떻게 되나요?

2024-12-20 04:29 UTC, eun-byeol commented on src/test/java/coupon/coupon/service/CouponServiceTest.java
> +        });
[의견]
에러 반환 여부뿐만 아니라, DB에 값이 바뀌었는지도 확인해주면 어떤가요?

2024-12-21 15:29 UTC, cutehumanS2 approved these changes
리니 ~ 🐶(< 멍구임) 안녕하세요. 냥인입니다. =ↀ.ↀ=
리뷰가 넘 늦어졌죠.. 죄송합니다 ㅠ.ㅠ

낙관적 락 방식을 선택하셨군여~~ 저랑 같아서 뭔가 반가워요.ㅎ ㅎ
리니는 요구사항을 꼼꼼히 분석하는 능력이 좋네요. 칭찬 백만 개 드림~👍 

조조가 아주 야무지게 질문 남겨주셔서 저는 쫌쫌따리 달아보았어요. 
천천히 확인해 주셔요~~✿ܓ

> 이미 고객이 사용할 수 있게 공개된 쿠폰을 중간에 수정할 가능성은 적다고 생각합니다. 그렇다면 아직 발급 불가능한 쿠폰 정보를 수정할텐데, 제약 조건을 위반하는 쿠폰이라면 제거 후, 다시 생성하는 선택지도 있다고 생각합니다.
> 

→ 사용자와 도메인 관점, 모두를 고려한 균형잡힌 접근이 인상깊어요. 굿.

<br>

> 확실한 데이터 정합성 보장은 가능하다는 장점이 있지만, **두 데이터의 저장소를 분리하는 작업을 계획 중**이기 때문에 락 관리의 복잡성이 우려되었습니다.
> 

→ 완전 놓치고 있던 요구사항이네요. 같은 방식을 선택했지만, 선택 근거가 저보다 훨씬 풍부해요. 배워갑니다. ✦‿✦

<br>

> **MemberCoupon은 이미 특정 회원에게 발급 완료된 쿠폰인데, 사용자가 1000원 할인인 줄 알았던 쿠폰이 갑자기 500원 할인으로 바뀌어도 과연 괜찮은건가?**
정리하자면, **데이터 저장소를 분리하는 작업을 진행한다면 서로 다른 시스템에서 공유 자원에 접근하는 상황이 발생할 여지가 있다고 생각했습니다. 따라서, 분산 락 방식으로의 교체도 염두에 두고 있습니다.**
> 

리니의 의견에 동의합니다. 

Coupon과 MemberCoupon을 저장하는 DB가 분리된다면, 서비스의 일관성을 유지하기 위해 서로 다른 시스템에서 공유 자원에 접근하는 상황은 분명 발생할 것 같아요. 

그런 점에서 두 데이터의 저장소를 분리하는 작업이 이뤄진다면, 그땐 분산 락을 사용하는 게 필수적이라고 봅니다. 

추가로 조조의 의견대로 이미 회원에게 발급된 쿠폰의 정보는 수정하지 못하게 하는 로직이 보완된다면, 더 안전하고 신뢰할 수 있는 서비스가 될 거라 생각해요. 

좋은 고민점을 제시해 주셔서 감사합니다 리니~🩵

2024-12-21 15:29 UTC, cutehumanS2 commented on src/main/java/coupon/cache/CacheService.java
> +    @Cacheable(value = "coupons", key = "#p0")
#p0은 뭘 의미하나요~?

2024-12-21 15:29 UTC, cutehumanS2 commented on src/main/java/coupon/coupon/domain/Coupon.java
> +@DynamicUpdate
왜 3단계 미션에서 @DynamicUpdate를 적용하라 했을까요??

2024-12-21 15:29 UTC, cutehumanS2 commented on src/main/java/coupon/coupon/domain/Coupon.java
> +
완전 사소한 부분이지만ㅎ ㅎ 
여기 공백이 한 줄 들어갔어요~

2024-12-21 15:29 UTC, cutehumanS2 commented on src/main/java/coupon/coupon/domain/Coupon.java
> +    }
리니는 롬복을 사용하지 않는 것 같군요!
이유가 궁금해요~

2024-12-21 15:29 UTC, cutehumanS2 commented on src/main/java/coupon/util/OptimisticLockRetryAspect.java
> +    }
재시도 로직하면 (아마도) 늘 따라다니는 개념이 있는데요, 지수 백오프(Exponential Backoff)에 대해 알고 계신가요? 

반영은 안 하셔도 되지만, 한 번 알아보시면 좋을 것 같아요. ㅎ ㅎ

2024-12-21 15:29 UTC, cutehumanS2 commented on src/main/java/coupon/coupon/service/CouponService.java
> +    @Retry
낙관적 락 충돌이 발생했을 때, 재시도를 수행한 이유가 뭔가요?! 

재시도 없이 사용자에게 예외 메시지를 그대로 내려주는 등의 방법도 있었을 텐데, 리니의 구현 의도가 궁금해요~~~~ ✦‿✦

2024-12-21 15:29 UTC, cutehumanS2 commented on docker/init/schema.sql
> +    used       BOOLEAN     NOT NULL,
저도 자료형 관련 질문 남겨볼게요. ㅎ.ㅎ

- MySQL에서 BOOLEAN 타입은 실제로 어떤 타입으로 저장될까요?
    - 그 이유도 한번 가볍게 알아보셔요~~(꼭 여기 정리 안 해두 됨~)

2024-12-22 15:25 UTC, jongmee requested changes
다른 리뷰들과 궁금한 내용이 좀 겹쳐서 간단하게 남겨봤어요! 고생하셨습니다 ❤️ 🙇🏻‍♀️

2024-12-22 15:25 UTC, jongmee commented on src/main/java/coupon/coupon/domain/Coupon.java
> +package coupon.coupon.domain;
> 확실한 데이터 정합성 보장은 가능하다는 장점이 있지만, 두 데이터의 저장소를 분리하는 작업을 계획 중이기 때문에 락 관리의 복잡성이 우려되었습니다.

리니가 생각하는 (비관)`락 관리의 복잡성`의 구체적 예시가 궁금해요!! 👀

2024-12-22 15:25 UTC, jongmee commented on src/main/java/coupon/coupon/domain/Coupon.java
> +    @Version
LockModeType 별로 해결할 수 있는 문제, 발생할 수 있는 문제를 정리해보면 좋을 것 같아요!

2024-12-24 13:58 UTC, linirini commented on docker/init/schema.sql
> +    end_at               DATETIME(6)                                              NOT NULL,
### DATETIME
- `YYYY-MM-DD HH:MM:SS` 형식으로 저장됩니다.
- 범위는 `1000-01-01 00:00:00`부터 `9999-12-31 23:59:59`까지 가능합니다.
- 입력된 날짜와 시간을 문자열 그대로 저장하기 때문에, **특정 시간대에 의존하지 않습니다.**
### TIMESTAMP
- Unix Timestamp 형식으로 저장됩니다. ex) 2038-01-19 03:14:07 UTC
  - 예를 들어, 한국 시간대(KST)로 저장해도 내부적으로 UTC로 변환됩니다.
- `1970-01-01 00:00:01 UTC`부터 `2038-01-19 03:14:07 UTC`까지 가능합니다.
- 조회 시 MySQL 서버나 클라이언트의 **Time Zone** 설정에 따라 로컬 시간으로 변환됩니다.

따라서, DATETIME은 주로 시간대 변경과 관계없이 일정한 날짜와 시간을 유지할 때 사용하고, TIMESTAMP는 시간대에 민감하고 글로벌 시스템에서 UTC 시간 기준으로 작업해야 할 때 유용합니다.

2024-12-26 15:48 UTC, linirini commented on src/main/java/coupon/cache/CacheService.java
> +    @Cacheable(value = "coupons", key = "#p0")
#p0은 직접 0번째 매개변수 쓰겠다고 지정하는 것입니다!
캐시를 처음 적용하던 당시 분명 cache에 값이 저장된것도 확인을 했는데 불러와지지 않고, `java.lang.IllegalArgumentException: Null key returned for cache operation` 에러가 발생했어요🥲
[stackOverFlow](https://stackoverflow.com/questions/41319555/spring-cache-null-key-returned-for-cache-operation)에 따르면, -parameters 라는 플래그 없이 컴파일돼서 파라미터 이름을 못찾는 것 같습니다.! 그래서 id라는 파라미터 없다고 판단하여 위와 같은 에러를 발생시키는 것 같아요! 
당시에는 #p0으로 해서 직접 0번째 매개변수 쓰겠다고 지정해서 해결했었는데, 현재는 파라미터명으로 변경해도 해당 에러가 발생하지 않길래 수정해놓았습니다.. (안됐었는데, 되네요🤔ㅋㅋㅋ)

2024-12-26 15:49 UTC, linirini commented on src/main/java/coupon/coupon/service/CouponService.java
> +    @CachePut(value = "coupons", key = "#p0")
처음에 캐시를 적용하던 당시 키를 찾지 못하는 에러가 발생해서 파라미터 순서로 지정했었는데요, 지금은 되네요....? ㅋㅋㅋㅋㅋ ([참고](https://github.com/jewelry-box/java-coupon/pull/4#discussion_r1897990943))
적용했습니다👍👍

2024-12-26 16:59 UTC, linirini commented on src/main/java/coupon/coupon/domain/Coupon.java
> +    @Version
### JPA LockModeType

| **LockModeType**            | **설명**                                                                                     | **발생할 수 있는 문제**                                                                                     | **해결할 수 있는 문제**                                                                                     |
|-----------------------------|--------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------|
| `NONE`                      | 잠금 모드 없음 (기본값). 단순 조회 시 사용. 데이터 변경 충돌을 감지하지 않음.               | 동시에 수정 작업이 일어나면 데이터 불일치 가능성이 있음.                                                   | 데이터 충돌을 고려하지 않아도 되는 단순 조회 작업에서 성능 최적화 가능.                                    |
| `OPTIMISTIC`                | 낙관적 락 사용. `@Version` 필드를 사용해 변경 충돌을 감지. 데이터 읽기 시 버전 필드 확인.  | 데이터 충돌이 많을 경우 충돌 예외(`OptimisticLockException`)가 자주 발생하여 재시도가 필요.                  | 데이터 충돌 감지가 가능하며 읽기 작업에 락을 걸지 않아 성능을 유지.                                         |
| `OPTIMISTIC_FORCE_INCREMENT`| 낙관적 락 사용 및 버전 필드를 강제로 증가. 데이터 읽기와 동시에 버전 증가.                  | 읽기 작업에서도 불필요하게 버전 필드가 증가하여 성능 저하 가능.                                            | 데이터 충돌 감지와 동시에 읽기 작업이 트랜잭션 간 데이터 최신화를 요구하는 경우에 유용.                     |
| `PESSIMISTIC_READ`          | 비관적 읽기 락 사용. 다른 트랜잭션이 데이터를 읽을 수는 있지만, 수정은 불가능.            | 읽기 트랜잭션이 길어지면 교착 상태(Deadlock) 발생 가능.                                                    | 읽기 작업 중에 데이터 수정 방지. 읽기 작업에서도 데이터 무결성을 보장.                                     |
| `PESSIMISTIC_WRITE`         | 비관적 쓰기 락 사용. 다른 트랜잭션이 데이터 읽기 및 수정 모두 불가능.                     | 트랜잭션이 길어질 경우 다른 트랜잭션이 대기하면서 성능 저하 및 교착 상태 발생 가능.                          | 동시에 수정 작업 방지. 데이터 일관성을 보장하며 중요한 쓰기 작업 보호.                                     |
| `PESSIMISTIC_FORCE_INCREMENT`| 비관적 쓰기 락 사용 및 버전 필드를 강제로 증가.                                           | 불필요한 버전 필드 증가와 긴 트랜잭션으로 인해 성능 저하 및 교착 상태 발생 가능.                             | 데이터 수정 시 충돌 방지와 버전 필드 증가를 통해 최신 상태를 유지할 수 있음.                                |

추가로, `WRITE`와 `READ` 타입도 있지만, JPA 구현체에서 구체적인 동작이 명확히 정의되지 않았거나, `OPTMISITC`/ `PESSIMISTIC` 계열로 대체되어 사용됩니다.

2024-12-26 17:08 UTC, linirini commented on docker/init/schema.sql
> +    used       BOOLEAN     NOT NULL,
MySQL에서 BOOLEAN 타입은 **실제로 TINYINT(1)**로 저장됩니다.
`BOOLEAN`은 MySQL에서 별도의 데이터 타입이 아닙니다. 따라서, MySQL에서는 TINYINT(1) 타입으로 0은 `FALSE`, 1은 `TRUE`로 간주하여 처리합니다.
SQL 표준에서는 `BOOLEAN` 타입을 정의하고 있지만, MySQL은 이를 엄격히 준수하지 않고 자체적으로 구현했습니다. MySQL은 `BOOLEAN`이라는 이름만 제공하여 다른 DBMS와의 호환성을 높입니다.

2024-12-26 17:12 UTC, linirini commented on src/main/java/coupon/util/OptimisticLockRetryAspect.java
> +    }
지수 백오프(Exponential Backoff)는 재시도 로직에서 흔히 사용되는 전략으로, 실패한 요청을 다시 시도할 때 대기 시간을 점진적으로 증가시키는 방식입니다. 이는 시스템 부하를 줄이고, 충돌이나 과부하 문제를 완화하기 위한 효과적인 방법으로 널리 사용됩니다.
이름에서도 알 수 있듯, 초기 재시도는 비교적 짧은 대기 시간 후에 시도한다면, 이후부터는 재시도 간 대기 시간이 지수적으로 증가하는 방식입니다. 이때, 무한히 증가하지 않도록 최대 대기 시간을 설정하고, 대기 시간에 약간의 랜덤성을 추가하여 여러 클라이언트가 동일한 시간에 요청하지 않도록 충돌을 방지합니다.
지수 백오프 전략의 장점은 서버에 과도한 요청이 몰리는 것을 방지하고, 실패가 반복될수록 대기 시간을 늘려 네트워크 자원을 효율적으로 사용한다는 것입니다.

2024-12-26 17:13 UTC, linirini commented on src/main/java/coupon/coupon/domain/Coupon.java
> +    }
딱히 특별한 이유는 없었어요 ㅎㅎ
단지, 최근에는 롬복을 자주 사용했다보니 오랜만에 순정으로 돌아가보고 싶어서 사용했답니다:)

2024-12-26 18:23 UTC, linirini commented on src/main/java/coupon/coupon/domain/Coupon.java
> +@DynamicUpdate
`@DynamicUpdate`는 엔터티 업데이트 시 변경된 필드만 포함하는 SQL을 생성하도록 하는 어노테이션입니다. 
기본적으로 JPA는 엔터티를 업데이트할 때 엔터티의 모든 필드 값을 포함한 UPDATE 쿼리를 생성합니다. `@DynamicUpdate`를 사용하면 실제로 변경된 필드만 업데이트 쿼리에 포함되므로 트래픽을 줄이고 성능을 향상시킬 수 있습니다. 
기본적으로는 모든 필드를 포함한 UPDATE로 인해 트랜잭션 간 충돌 가능성이 증가하지만, @DynamicUpdate를 사용하면 각 트랜잭션이 필요한 필드만 수정하여 불필요한 충돌을 줄일 수 있습니다.

단, @DynamicUpdate는 필드의 변경 여부를 동적으로 판단하므로 실행 시점에 추가적인 연산 비용이 발생합니다. 따라서, 엔터티가 너무 자주 업데이트되거나 필드가 적은 경우에는 오히려 성능에 부정적인 영향을 줄 수 있습니다.

2024-12-26 18:40 UTC, linirini commented on docker/init/schema.sql
> +    used       BOOLEAN     NOT NULL,
> 낙관적 락 충돌이 발생했을 때, 재시도를 수행한 이유가 뭔가요?!
재시도 없이 사용자에게 예외 메시지를 그대로 내려주는 등의 방법도 있었을 텐데, 리니의 구현 의도가 궁금해요~~~~ ✦‿✦

처음에 냥냥이 말한 방법도 고려했었는데요, 제 의도는 이와 같습니다.
낙관적 락 충돌이 발생했을 때, 사용자에게 예외 메시지를 내려준다면 `누군가 쿠폰을 수정했어요. 다시 시도해주세요.`와 같은 방식이 될 것 같아요. **제약 조건 위반과 무관하게** 동시 수정을 시도만으로도 락 충돌은 발생하니까요!
하지만, 사용자 입장에서 예외 메시지가 충분히 구체적이지 않을 수 있겠다고 생각했습니다. 문제 상황은 동시 수정을 시도했을 때 **제약 조건을 위반하는 쿠폰이 생성되는 상황**인 것이지, 동시 수정 자체가 문제가 되는 것은 아니라고 생각했어요. 
그렇기 때문에 **동시 수정 상황이 발생했다면 사용자가 감안할 수 있는 지연 시간 내에서 재시도를 하여 제약 조건을 위반하는 쿠폰이 생성되는 경우에만 예외를 반환할 수 있다면 사용자에게 더 좋은 경험을 제공할 수 있지 않을까?**생각해보았어요!
냥냥의 생각은 어떤지 궁금해요><

2024-12-26 18:44 UTC, linirini commented on src/main/java/coupon/coupon/service/CouponService.java
> +    @Retry
>낙관적 락 충돌이 발생했을 때, 재시도를 수행한 이유가 뭔가요?!
재시도 없이 사용자에게 예외 메시지를 그대로 내려주는 등의 방법도 있었을 텐데, 리니의 구현 의도가 궁금해요~~~~ ✦‿✦

처음에 냥냥이 말한 방법도 고려했었는데요, 제 의도는 이와 같습니다.
낙관적 락 충돌이 발생했을 때, 사용자에게 예외 메시지를 내려준다면 누군가 쿠폰을 수정했어요. 다시 시도해주세요.와 같은 방식이 될 것 같아요. 제약 조건 위반과 무관하게 동시 수정을 시도만으로도 락 충돌은 발생하니까요!
하지만, 사용자 입장에서 예외 메시지가 충분히 구체적이지 않을 수 있겠다고 생각했습니다. 문제 상황은 동시 수정을 시도했을 때 제약 조건을 위반하는 쿠폰이 생성되는 상황인 것이지, 동시 수정 자체가 문제가 되는 것은 아니라고 생각했어요.
그렇기 때문에 **동시 수정 상황이 발생했다면 사용자가 감안할 수 있는 지연 시간 내에서 재시도를 하여 제약 조건을 위반하는 쿠폰이 생성되는 경우에만 예외를 반환할 수 있다면 사용자에게 더 좋은 경험을 제공할 수 있지 않을까?**생각해보았어요!
냥냥의 생각은 어떤지 궁금해요><

2024-12-26 21:29 UTC, linirini commented on src/main/java/coupon/coupon/service/CouponService.java
> +    @Retry
> springboot의 @Retryable를 사용하지 않고 직접 AOP로 만들어준 이유가 있을까요?🤔

`@Retryable`이 있다는 걸 모르고 있었네요😮
조조 덕분에 또 하나 배워갑니다 ㅎㅎ
Spring에서 제공해주는 @Retryable을 사용하도록 리팩터링 해봤습니다! `@Retryable` 내부적으로 지수 백오프나, 어떤 예외에 재시도를 할지/안할지 등 여러 옵션을 제공해줘서 편리하게 재시도 로직을 구현할 수 있었어요👍👍

2024-12-26 22:29 UTC, linirini commented on src/main/java/coupon/util/OptimisticLockRetryAspect.java
> +@Order(Ordered.LOWEST_PRECEDENCE - 1)
우선순위를 Transaction보다 높게 설정하여 트랜잭션 내부에서 충돌을 해결하기 위한 재시도 로직을 적용하기 위한 설정입니다.
LOWEST_PRECEDENCE가 일반적으로 디폴트입니다. 따라서, 우선순위를 따로 설정하지 않으면, `@Transactional` 어노테이션과 `@Retryable` 어노테이션의 순서를 보장할 수 없습니다. 즉, Transactional이 먼저 실행된다면, 재시도마다 트랜잭션이 달라지는 문제가 발생할 수 있습니다. 따라서, LOWEST_PRECEDENCE - 1로 설정하여 `@Retryable`이 기본 실행 순서 바로 직전에 실행되도록 만들었습니다.

2024-12-26 22:36 UTC, linirini commented on src/main/java/coupon/util/OptimisticLockRetryAspect.java
> +    private static final int RETRY_DELAY_MILLISECONDS = 100;
> 재시도 횟수와 딜레이를 설정한 근거가 궁금해요!

(리팩토링 과정에서 500ms마다 4회까지 시도하도록 수정했습니다!)
낙관적 락은 엔티티를 읽어올 때 락을 획득하고, 트랜잭션 커밋 시점에 해제됩니다.
따라서, 재시도 딜레이는 해당 트랜잭션 응답 시간을 확인하여 설정하였습니다. 확인 결과, 대략 500ms가 소요되는 것을 확인해서 500ms마다 사용자가 불편하지 않을 최대 지연 시간은 2초라고 가정하고 최대 시도 횟수를 4회로 설정해보았어요!
대략적으로 설정해본 값이고, 실제로는 서버 성능과 TPS에 따라 최대 지연 시간을 설정해볼 수 있지 않을까 막연하게 생각해보았습니다. ㅎㅎ

> 지금은 update를 위한 재시도 로직밖에 없지만, 다른 로직을 위한 재시도가 생긴다면 어떻게 되나요?

`@Retryable`은 [문서](https://docs.spring.io/spring-retry/docs/api/current/org/springframework/retry/annotation/Retryable.html)에서 확인할 수 있듯, 다양한 옵션을 제공합니다. 해당 옵션들을 적절히 활용하여 상황에 맞게 재시도 로직을 구현할 수 있을 거라고 생각합니다:)

2024-12-26 22:43 UTC, linirini commented on src/test/java/coupon/coupon/service/CouponServiceTest.java
> +        });
좋은 것 같아요! 반영했습니다~

2024-12-26 23:26 UTC, linirini commented on src/main/java/coupon/coupon/domain/Coupon.java
> +    @Version
놓치고 있었어요....ㅎㅎ 짚어주셔서 감사합니다!
동시 수정이 자주 발생하지 않는다는 가정 하에 읽기에는 버전을 체크하지 않는 `OPTIMISTIC`으로 옵션을 수정해보았습니다!

2024-12-26 23:32 UTC, linirini commented on src/main/java/coupon/coupon/domain/Coupon.java
> +package coupon.coupon.domain;
현재 저는 다음과 같은 방식으로 데이터베이스를 분리한다고 가정했어요!
- Coupon DB: 쿠폰의 기본 정보를 저장.
- MemberCoupon DB: 회원이 보유한 쿠폰 정보를 저장.

예를 들어, 위와 같이 저장소를 분리하여 관리했을 때, 하나의 트랜잭션에서 두 저장소 모두 참조해야한다면 데이터베이스 레벨에서는 이와 같은 다중 데이터베이스 트랜잭션 관리가 복잡해질 수 있다고 생각했어요.

2025-01-04 08:08 UTC, eun-byeol approved these changes
리니~🐶 고생하셨어요!
답변 달아준 부분들 확인했어요. 논리적으로 답변 잘 해주셔서 덕분에 저도 배웠어요👍
몇가지 리뷰 더 남겼으니 확인해주세요!
이만 approve 합니다! 새해 복 많이 받으세용❤️

2025-01-04 08:08 UTC, eun-byeol commented on src/main/java/coupon/coupon/domain/Coupon.java
> +package coupon.coupon.domain;
음.. 락은 데이터베이스가 해주는 부분이라 개발자 입장에선 크게 고려해야 할 부분은 없어보이는데, 고려해야 할 다른 상황이 있을까요?🤔

2025-01-04 08:08 UTC, eun-byeol commented on src/main/java/coupon/coupon/domain/Coupon.java
> +    @Version
> `@Version`만 붙이면 기본적으로 LockModeType.NONE으로 지정되는 것으로 알고 있는데

잘못 말씀드린 부분이 있어요. 기본 설정값이 어떤건 지 헷갈리네요🥲
[블로그](https://velog.io/@lsb156/JPA-Optimistic-Lock-Pessimistic-Lock#%EB%82%99%EA%B4%80%EC%A0%81-%EC%9E%A0%EA%B8%88%EC%9D%98-lockmodetype)엔 디폴트가 NONE으로 되어 있었는데, 직접 코드로 확인해보았는데 OPTIMISTIC으로 실행되네요.

아래 코드로 확인해보았어요.
```java
    @Transactional
    @Retryable(retryFor = {OptimisticLockException.class, ObjectOptimisticLockingFailureException.class, StaleObjectStateException.class},
            maxAttempts = 4,
            backoff = @Backoff(delay = 500))
    @CachePut(value = "coupon", key = "#id")
    public Coupon updateCouponMinimumOrderAmount(long id, MinimumOrderAmountRequest request) {
        MinimumOrderAmount minimumOrderAmount = request.toMinimumOrderAmount();
        Coupon coupon = cacheService.getCoupon(id);
        coupon.changeMinimumOrderAmount(minimumOrderAmount);
        LockModeType lockMode = entityManager.getLockMode(coupon); // 추가
        System.out.println("---- LockModeType " + lockMode); // 추가
        return coupon;
    }
```

2025-01-04 08:08 UTC, eun-byeol commented on src/main/java/coupon/coupon/domain/Coupon.java
> +    @Version
> 지금은 동시성 문제 발생 가능성이 낮기 때문에, 조회 시점의 락이 꼭 필요하지 않다고 생각했는데, 조조의 생각은 어떤지 궁금해요!

저는 OPTIMISTIC으로 처리할 것 같아요. 동시성 발생 가능성이 낮긴 하지만, 가능성이 완전히 없진 않으니까요. 금액이라는 중요한 도메인일수록 데이터 부정합 문제를 예방하는게 중요하다고 생각해요. OPTIMISTIC 또한 실제로 락을 걸지 않아서, 비관적 락보다 성능저하 우려도 크지 않을 것 같습니다~

2025-01-04 08:08 UTC, eun-byeol commented on src/main/java/coupon/coupon/domain/Coupon.java
> +    @Version
NONE의 경우 잠금 모드 없음 (기본값)인지 더블체크가 필요할 것 같아요!
저는 블로그 외 문서를 찾지 못했는데, 혹시 발견하심 공유해주시면 감사드리겠습니다🙇‍♀️

2025-01-04 08:08 UTC, eun-byeol commented on src/main/java/coupon/cache/CacheService.java
> +    //@Cacheable(value = "coupon", key = "#memberCoupon.couponId")
[질문]
주석처리 된 부분은 아직 해결되지 않은 건가요?🤔

2025-01-06 04:24 UTC, linirini commented on src/main/java/coupon/coupon/domain/Coupon.java
> +    @Version
> 저는 OPTIMISTIC으로 처리할 것 같아요. 동시성 발생 가능성이 낮긴 하지만, 가능성이 완전히 없진 않으니까요. 금액이라는 중요한 도메인일수록 데이터 부정합 문제를 예방하는게 중요하다고 생각해요. OPTIMISTIC 또한 실제로 락을 걸지 않아서, 비관적 락보다 성능저하 우려도 크지 않을 것 같습니다~

인정합니당><

2025-01-06 07:22 UTC, linirini commented on src/main/java/coupon/cache/CacheService.java
> +    //@Cacheable(value = "coupon", key = "#memberCoupon.couponId")
넹.....ㅜㅜ 추측상 트랜잭션 AOP 동작 시점과 꼬이지 않았을까...싶습니다

2025-01-14 08:03 UTC, jongmee commented on src/main/java/coupon/coupon/domain/Coupon.java
> +package coupon.coupon.domain;
서로 다른 저장소에 저장된다면 락을 외부에서 관리해야 겠군요 😙

2025-01-14 08:22 UTC, jongmee approved these changes
남겨준 코멘트 잘 읽었습니다! 고생하셨읍니다 리니 🤍

2025-02-08 11:56 UTC, merged